\newcommand{\volDisp}{\mathrm{Subme}}

## Automation
  - In which I pick a problem to automate and tell you a little about it
  
## Automated Design
  - As functional minimization (extrema finding) sets the stage

## Automatic Differentiation 
  - Programming without (as much) _programming_
  
## Interval constraint programming  
  - Design without (as much) _search_
  
## Results
  - If your going to solve a problem, eventually you have to... solve a problem.

Pick a Problem, automate the generation of this kind of thing:

![title](fig/RapidHull.png)

(NURBS hullform in demo in Rhino, human created)

In [120]:
import warnings
warnings.filterwarnings('ignore') #sorry, I've got old code that needs updating -- shame on me!



This is called,

## Early Stage Ship Hull Design

Why would we want to work on this?

$$ 
\begin{align*}
\nabla &: \text{Displacement} \\
\text{L}_{\text{WL}} &: \text{waterline length} \\
\end{align*}
$$

In [121]:
import relational_lsplines as rsp #my stuff

import numpy as np #linear algebra

In [122]:

np.set_printoptions(precision=3)

In [123]:
curve = rsp.curve #Bspline curve and surface module


automatic_differentiation = rsp.automatic_differentiation #automatic_differentiation "module"
                    # simple fwd mode with vectors and intervals supported

adObjectMaker = automatic_differentiation.adObjectMaker

ad = automatic_differentiation.ad                   #automatic differentiation class


In [124]:
num_in_vec = 2  # problem space size

identity = np.identity(num_in_vec)

nullmatrix = np.zeros((num_in_vec,num_in_vec),float)

In [125]:
x0 = ad( 2., 
        grad = identity[0], 
        hess = nullmatrix, 
        of_scalars=True)

print 'x0.value = ',x0.value
print 'x0.grad  = ', x0.grad
print 'x0.hess  = '
print x0.hess

x0.value =  2.0
x0.grad  =  [1. 0.]
x0.hess  = 
[[0. 0.]
 [0. 0.]]


So we have created a variable, x0

We gave it a gradient and hessian associated with it, 
with sizes denoted by the problem space. 

Later, this part will be automated too.


In [126]:
x1 = ad( 2., 
        grad = identity[1], 
        hess = nullmatrix, 
        of_scalars=True)

print ''
print 'x1.value = ',x1.value
print 'x1.grad  = ', x1.grad
print 'x1.hess  = '
print x1.hess


x1.value =  2.0
x1.grad  =  [0. 1.]
x1.hess  = 
[[0. 0.]
 [0. 0.]]


In [127]:
test = x0 + x1**2
print '\ntest value'
print test.value
print '\ntest gradient'
print test.grad
print '\ntest hessian'
print test.hess


test value
6.0

test gradient
[1. 4.]

test hessian
[[2. 2.]
 [2. 2.]]


## (Interval) Constraint Programming

"A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away."  - Antoine de Saint-Exupéry

Sorry, that's melodramatic.  
I just fed my data into a slide generator algorithm.  
I didn't have time to clean it up after.